version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: jaidee-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - backend_data:/app/data
    restart: unless-stopped
    networks:
      - jaidee-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Service
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: jaidee-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - jaidee-network
    environment:
      - REACT_APP_API_URL=http://localhost:3001

volumes:
  backend_data:
    driver: local

networks:
  jaidee-network:
    driver: bridge